# Tratando erros de forma segura

Linha 67 ate 69

````
const existePacienteComCPF = await AppDataSource.getRepository(Paciente).findOne({
    where: { cpf }
})
if (existePacienteComCPF != null) {
    throw new AppError('Já existe um paciente com esse CPF!', Status.CONFLICT)
}
````



Linha 109 ate Linha 111

````
  res.status(202).json (pacienteSemDadosSensiveis)
  } catch (error) {
  console.log(error)
  throw new AppError('Paciente não foi criado', Status.
  BAD_GATEWAY)
  }
````

* Arquivo arrumado e correto.
- pacienteControler.ts